### ISSUE TITLE
Empty screen, when the app been launched.

### ISSUE THREAD

**Issue by daimajia** [yeziahehe/Gank#6]
I have no idea why this happened. 

----

![image](https://cloud.githubusercontent.com/assets/2503423/21876665/e6ac4718-d8bf-11e6-852f-f7c83bc6f160.png)

**Comment by yeziahehe** [comment]
@daimajia Hi, I have Complete this project now, and I have post gank to gank.io this morning but not post in today's gank. I am so so so sad~

**Comment by daimajia** [comment]
@yeziahehe Thanks a lot, pretty awesome.

**Comment by yeziahehe** [comment]
@daimajia Next Monday don't forget post this in gank.io, thanks!
